// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: proto_files/cash/cash.proto

package cash

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CashId     int64   `protobuf:"varint,1,opt,name=cashId,proto3" json:"cashId,omitempty"`
	Amount     float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Summary    string  `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	ReceivedAt string  `protobuf:"bytes,4,opt,name=receivedAt,proto3" json:"receivedAt,omitempty"`
}

func (x *Cash) Reset() {
	*x = Cash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_cash_cash_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cash) ProtoMessage() {}

func (x *Cash) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_cash_cash_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cash.ProtoReflect.Descriptor instead.
func (*Cash) Descriptor() ([]byte, []int) {
	return file_proto_files_cash_cash_proto_rawDescGZIP(), []int{0}
}

func (x *Cash) GetCashId() int64 {
	if x != nil {
		return x.CashId
	}
	return 0
}

func (x *Cash) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Cash) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Cash) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

type Identificator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *Identificator) Reset() {
	*x = Identificator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_cash_cash_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identificator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identificator) ProtoMessage() {}

func (x *Identificator) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_cash_cash_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identificator.ProtoReflect.Descriptor instead.
func (*Identificator) Descriptor() ([]byte, []int) {
	return file_proto_files_cash_cash_proto_rawDescGZIP(), []int{1}
}

func (x *Identificator) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Identificator) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PostCash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identificator *Identificator `protobuf:"bytes,1,opt,name=identificator,proto3" json:"identificator,omitempty"`
	Amount        float64        `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Summary       string         `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
}

func (x *PostCash) Reset() {
	*x = PostCash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_cash_cash_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostCash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCash) ProtoMessage() {}

func (x *PostCash) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_cash_cash_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCash.ProtoReflect.Descriptor instead.
func (*PostCash) Descriptor() ([]byte, []int) {
	return file_proto_files_cash_cash_proto_rawDescGZIP(), []int{2}
}

func (x *PostCash) GetIdentificator() *Identificator {
	if x != nil {
		return x.Identificator
	}
	return nil
}

func (x *PostCash) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PostCash) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ListOfCashe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cashes []*Cash `protobuf:"bytes,1,rep,name=cashes,proto3" json:"cashes,omitempty"`
}

func (x *ListOfCashe) Reset() {
	*x = ListOfCashe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_cash_cash_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfCashe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfCashe) ProtoMessage() {}

func (x *ListOfCashe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_cash_cash_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfCashe.ProtoReflect.Descriptor instead.
func (*ListOfCashe) Descriptor() ([]byte, []int) {
	return file_proto_files_cash_cash_proto_rawDescGZIP(), []int{3}
}

func (x *ListOfCashe) GetCashes() []*Cash {
	if x != nil {
		return x.Cashes
	}
	return nil
}

var File_proto_files_cash_cash_proto protoreflect.FileDescriptor

var file_proto_files_cash_cash_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x63, 0x61,
	0x73, 0x68, 0x2f, 0x63, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63,
	0x61, 0x73, 0x68, 0x22, 0x70, 0x0a, 0x04, 0x43, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x61, 0x73, 0x68, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x61, 0x73,
	0x68, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x64, 0x41, 0x74, 0x22, 0x47, 0x0a, 0x0d, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x77,
	0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x43, 0x61, 0x73, 0x68, 0x12, 0x39, 0x0a, 0x0d, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x63, 0x61, 0x73, 0x68, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x0d, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x31, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x66, 0x43, 0x61, 0x73, 0x68, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x63, 0x61, 0x73, 0x68, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63, 0x61, 0x73, 0x68, 0x2e, 0x43, 0x61,
	0x73, 0x68, 0x52, 0x06, 0x63, 0x61, 0x73, 0x68, 0x65, 0x73, 0x32, 0x76, 0x0a, 0x0b, 0x43, 0x61,
	0x73, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x0b, 0x50, 0x6f, 0x73,
	0x74, 0x4e, 0x65, 0x77, 0x43, 0x61, 0x73, 0x68, 0x12, 0x0e, 0x2e, 0x63, 0x61, 0x73, 0x68, 0x2e,
	0x50, 0x6f, 0x73, 0x74, 0x43, 0x61, 0x73, 0x68, 0x1a, 0x0a, 0x2e, 0x63, 0x61, 0x73, 0x68, 0x2e,
	0x43, 0x61, 0x73, 0x68, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x4f, 0x66, 0x43, 0x61, 0x73, 0x68, 0x65, 0x12, 0x13, 0x2e, 0x63, 0x61, 0x73, 0x68, 0x2e,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x1a, 0x11, 0x2e,
	0x63, 0x61, 0x73, 0x68, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x43, 0x61, 0x73, 0x68, 0x65,
	0x22, 0x00, 0x42, 0x19, 0x5a, 0x17, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x63, 0x61, 0x73, 0x68, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_files_cash_cash_proto_rawDescOnce sync.Once
	file_proto_files_cash_cash_proto_rawDescData = file_proto_files_cash_cash_proto_rawDesc
)

func file_proto_files_cash_cash_proto_rawDescGZIP() []byte {
	file_proto_files_cash_cash_proto_rawDescOnce.Do(func() {
		file_proto_files_cash_cash_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_files_cash_cash_proto_rawDescData)
	})
	return file_proto_files_cash_cash_proto_rawDescData
}

var file_proto_files_cash_cash_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_files_cash_cash_proto_goTypes = []interface{}{
	(*Cash)(nil),          // 0: cash.Cash
	(*Identificator)(nil), // 1: cash.Identificator
	(*PostCash)(nil),      // 2: cash.PostCash
	(*ListOfCashe)(nil),   // 3: cash.ListOfCashe
}
var file_proto_files_cash_cash_proto_depIdxs = []int32{
	1, // 0: cash.PostCash.identificator:type_name -> cash.Identificator
	0, // 1: cash.ListOfCashe.cashes:type_name -> cash.Cash
	2, // 2: cash.CashService.PostNewCash:input_type -> cash.PostCash
	1, // 3: cash.CashService.GetListOfCashe:input_type -> cash.Identificator
	0, // 4: cash.CashService.PostNewCash:output_type -> cash.Cash
	3, // 5: cash.CashService.GetListOfCashe:output_type -> cash.ListOfCashe
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_files_cash_cash_proto_init() }
func file_proto_files_cash_cash_proto_init() {
	if File_proto_files_cash_cash_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_files_cash_cash_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_cash_cash_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identificator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_cash_cash_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostCash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_cash_cash_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOfCashe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_files_cash_cash_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_files_cash_cash_proto_goTypes,
		DependencyIndexes: file_proto_files_cash_cash_proto_depIdxs,
		MessageInfos:      file_proto_files_cash_cash_proto_msgTypes,
	}.Build()
	File_proto_files_cash_cash_proto = out.File
	file_proto_files_cash_cash_proto_rawDesc = nil
	file_proto_files_cash_cash_proto_goTypes = nil
	file_proto_files_cash_cash_proto_depIdxs = nil
}
