// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: proto_files/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int64   `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Fullname   string  `protobuf:"bytes,2,opt,name=Fullname,proto3" json:"Fullname,omitempty"`
	UserName   string  `protobuf:"bytes,3,opt,name=UserName,proto3" json:"UserName,omitempty"`
	TotalMoney float64 `protobuf:"fixed64,4,opt,name=TotalMoney,proto3" json:"TotalMoney,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_user_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_user_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_files_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetTotalMoney() float64 {
	if x != nil {
		return x.TotalMoney
	}
	return 0
}

type PostUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Fullname string `protobuf:"bytes,2,opt,name=Fullname,proto3" json:"Fullname,omitempty"`
	UserName string `protobuf:"bytes,3,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *PostUser) Reset() {
	*x = PostUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_user_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUser) ProtoMessage() {}

func (x *PostUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_user_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUser.ProtoReflect.Descriptor instead.
func (*PostUser) Descriptor() ([]byte, []int) {
	return file_proto_files_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *PostUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostUser) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *PostUser) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *PostUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetBasicInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Password string `protobuf:"bytes,1,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *GetBasicInfo) Reset() {
	*x = GetBasicInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_user_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasicInfo) ProtoMessage() {}

func (x *GetBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_user_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasicInfo.ProtoReflect.Descriptor instead.
func (*GetBasicInfo) Descriptor() ([]byte, []int) {
	return file_proto_files_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetBasicInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ListOfPostedUsersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListOfPostedUsersReq) Reset() {
	*x = ListOfPostedUsersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_user_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfPostedUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfPostedUsersReq) ProtoMessage() {}

func (x *ListOfPostedUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_user_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfPostedUsersReq.ProtoReflect.Descriptor instead.
func (*ListOfPostedUsersReq) Descriptor() ([]byte, []int) {
	return file_proto_files_user_user_proto_rawDescGZIP(), []int{3}
}

type ListOfPostedUsersRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllUsers []*PostUser `protobuf:"bytes,1,rep,name=AllUsers,proto3" json:"AllUsers,omitempty"`
}

func (x *ListOfPostedUsersRes) Reset() {
	*x = ListOfPostedUsersRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_user_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfPostedUsersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfPostedUsersRes) ProtoMessage() {}

func (x *ListOfPostedUsersRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_user_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfPostedUsersRes.ProtoReflect.Descriptor instead.
func (*ListOfPostedUsersRes) Descriptor() ([]byte, []int) {
	return file_proto_files_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *ListOfPostedUsersRes) GetAllUsers() []*PostUser {
	if x != nil {
		return x.AllUsers
	}
	return nil
}

var File_proto_files_user_user_proto protoreflect.FileDescriptor

var file_proto_files_user_user_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x22, 0x76, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x22, 0x76, 0x0a, 0x08, 0x50,
	0x6f, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x46, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x46, 0x75, 0x6c, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x2a, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22,
	0x16, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x22, 0x42, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x66, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x12,
	0x2a, 0x0a, 0x08, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x08, 0x41, 0x6c, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x73, 0x32, 0xb9, 0x01, 0x0a, 0x0a,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x0b, 0x50, 0x6f,
	0x73, 0x74, 0x4e, 0x65, 0x77, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x0a, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x1a,
	0x0a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x22, 0x00, 0x12, 0x48, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x50, 0x6f, 0x73, 0x74, 0x65,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x19, 0x5a, 0x17, 0x77, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_files_user_user_proto_rawDescOnce sync.Once
	file_proto_files_user_user_proto_rawDescData = file_proto_files_user_user_proto_rawDesc
)

func file_proto_files_user_user_proto_rawDescGZIP() []byte {
	file_proto_files_user_user_proto_rawDescOnce.Do(func() {
		file_proto_files_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_files_user_user_proto_rawDescData)
	})
	return file_proto_files_user_user_proto_rawDescData
}

var file_proto_files_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_files_user_user_proto_goTypes = []interface{}{
	(*User)(nil),                 // 0: user.User
	(*PostUser)(nil),             // 1: user.PostUser
	(*GetBasicInfo)(nil),         // 2: user.GetBasicInfo
	(*ListOfPostedUsersReq)(nil), // 3: user.ListOfPostedUsersReq
	(*ListOfPostedUsersRes)(nil), // 4: user.ListOfPostedUsersRes
}
var file_proto_files_user_user_proto_depIdxs = []int32{
	1, // 0: user.ListOfPostedUsersRes.AllUsers:type_name -> user.PostUser
	1, // 1: user.UserSevice.PostNewUser:input_type -> user.PostUser
	2, // 2: user.UserSevice.GetUserBasicInfo:input_type -> user.GetBasicInfo
	3, // 3: user.UserSevice.GetUsersList:input_type -> user.ListOfPostedUsersReq
	0, // 4: user.UserSevice.PostNewUser:output_type -> user.User
	0, // 5: user.UserSevice.GetUserBasicInfo:output_type -> user.User
	4, // 6: user.UserSevice.GetUsersList:output_type -> user.ListOfPostedUsersRes
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_files_user_user_proto_init() }
func file_proto_files_user_user_proto_init() {
	if File_proto_files_user_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_files_user_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_user_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_user_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBasicInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_user_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOfPostedUsersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_user_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOfPostedUsersRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_files_user_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_files_user_user_proto_goTypes,
		DependencyIndexes: file_proto_files_user_user_proto_depIdxs,
		MessageInfos:      file_proto_files_user_user_proto_msgTypes,
	}.Build()
	File_proto_files_user_user_proto = out.File
	file_proto_files_user_user_proto_rawDesc = nil
	file_proto_files_user_user_proto_goTypes = nil
	file_proto_files_user_user_proto_depIdxs = nil
}
